// Code generated by go2go; DO NOT EDIT.


//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:1
package peds

//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:1
import (
//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:1
 "fmt"
//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:1
 "math"
//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:1
 "runtime"
//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:1
 "strings"
//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:1
 "testing"
//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:1
 "unsafe"
//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:1
)

//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:5
const shiftSize = 5
const nodeSize = 32
const shiftBitMask = 0x1F

func uintMin(a, b uint) uint {
	if a < b {
		return a
	}

	return b
}

//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:20
type commonNode interface{}

//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:21
var emptyCommonNode commonNode = []commonNode{}

//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:91
func newPath(shift uint, node commonNode) commonNode {
	if shift == 0 {
		return node
	}

	return newPath(shift-shiftSize, commonNode([]commonNode{node}))
}

//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:217
func assertSliceOk(start, stop, len int) {
	if start < 0 {
		panic(fmt.Sprintf("Invalid slice index %d (index must be non-negative)", start))
	}

	if start > stop {
		panic(fmt.Sprintf("Invalid slice index: %d > %d", start, stop))
	}

	if stop > len {
		panic(fmt.Sprintf("Slice bounds out of range, start=%d, stop=%d, len=%d", start, stop, len))
	}
}

//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:229
type Importable୦ int

//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:229
var _ = fmt.Errorf
//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:229
var _ = math.Abs
//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:229
var _ = runtime.BlockProfile

//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:229
type _ strings.Builder

//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:229
var _ = testing.AllocsPerRun

//line /home/tobias/Development/go/peds/go2go/src/peds/containers.go2:229
type _ unsafe.Pointer
