// Code generated by go2go; DO NOT EDIT.


//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:1
package peds

//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:1
import (
//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:1
 "fmt"
//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:1
 "math"
//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:1
 "runtime"
//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:1
 "strings"
//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:1
 "testing"
//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:1
 "unsafe"
//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:1
)

//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:8
const upperMapLoadFactor float64 = 8.0
const lowerMapLoadFactor float64 = 2.0
const initialMapLoadFactor float64 = (upperMapLoadFactor + lowerMapLoadFactor) / 2

//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:19
func nilinterhash(p unsafe.Pointer, h uintptr) uintptr { return 0 }

//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:22
func genericHash(x interface{}) uint32 {
	return uint32(nilinterhash(unsafe.Pointer(&x), 0))
}

//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:24
var _ = fmt.Errorf
//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:24
var _ = math.Abs
//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:24
var _ = runtime.BlockProfile

//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:24
type _ strings.Builder

//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:24
var _ = testing.AllocsPerRun

//line /home/tobias/Development/go/peds/go2go/src/peds/map.go2:24
type _ unsafe.Pointer
